version: '3.8'

services:
  film-db:
    image: postgres:16
    environment:
      POSTGRES_USER: film_user
      POSTGRES_PASSWORD: film_password
      POSTGRES_DB: film_db
    ports:
      - "5433:5432"
    volumes:
      - film_db_data:/var/lib/postgresql/data

  film-microservice:
    build: .
    ports:
      - "3003:3003"
    environment:
      DATABASE_URL: postgresql://film_user:film_password@film-db:5432/film_db
      NODE_ENV: development
    depends_on:
      - film-db
    command: npm run start:dev

volumes:
  film_db_data:
